version: '3'
services:
  edu_database:
    image: postgres:14
    ports:
      - 5555:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1111
      - POSTGRES_DB=edu
  web:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - cats_database
    environment:
      - DB_HOST=edu_database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=1111
      - DB_NAME=cats_db